image: tcitworld/ex_optimizer-ci:latest

stages:
  - check
  - test
  - deploy

before_script:
  - mix deps.get

check:
  stage: check
  script:
    - mix credo -a
    - mix format --check-formatted --dry-run

mix:
  stage: test
  script:
    - mix coveralls

pages:
  stage: deploy
  script:
    - mix docs
    - mv doc/ public/
  only:
    - master
  artifacts:
    expire_in: 1 hour
    paths:
      - public
