image: elixir:latest

stages:
  - check
  - test
  - deploy

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

check:
  stage: check
  before_script:
    - mix deps.get
  script:
    - mix credo -a
    - mix format --check-formatted --dry-run

mix:
  stage: test
  before_script:
    - mix deps.get
  script:
    - mix coveralls

pages:
  stage: deploy
  before_script:
    - mix deps.get
  script:
    - mkdir public
    - mix docs
    - mv doc public
  only:
    - master
  artifacts:
    expire_in: 1 hour
    paths:
      - public
